/**
 * Data Source Configuration
 * This file is auto-generated by GitHub Actions during deployment
 * DO NOT EDIT MANUALLY
 *
 * The repository information is injected during the CI/CD build process
 * to enable fetching data from the data branch
 */

const DATA_CONFIG = {
    /**
     * GitHub repository owner (username)
     * This will be replaced during GitHub Actions workflow execution
     */
    repoOwner: 'Jiayihua2001',

    /**
     * GitHub repository name
     * This will be replaced during GitHub Actions workflow execution
     */
    repoName: 'daily-arXiv-ai-enhanced',

    /**
     * Data branch name
     * Default: 'data'
     */
    dataBranch: 'data',

    /**
     * Fallback (upstream) used when the user's own data branch 404s —
     * keeps the site usable while their daily pipeline is being set up.
     */
    fallbackOwner: 'dw-dengwei',
    fallbackRepo:  'daily-arXiv-ai-enhanced',

    /**
     * Get the base URL for raw GitHub content from data branch
     */
    getDataBaseUrl: function() {
        return `https://raw.githubusercontent.com/${this.repoOwner}/${this.repoName}/${this.dataBranch}`;
    },

    getFallbackBaseUrl: function() {
        return `https://raw.githubusercontent.com/${this.fallbackOwner}/${this.fallbackRepo}/${this.dataBranch}`;
    },

    /**
     * Full URL for a data file on the user's own data branch.
     */
    getDataUrl: function(filePath) {
        return `${this.getDataBaseUrl()}/${filePath}`;
    },

    /**
     * Same path on the upstream fallback (returns null if fallback === primary).
     */
    getFallbackUrl: function(filePath) {
        if (this.fallbackOwner === this.repoOwner &&
            this.fallbackRepo  === this.repoName) return null;
        return `${this.getFallbackBaseUrl()}/${filePath}`;
    }
};

